name: Lint & mypy check

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint-check-job:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9]
                poetry-version: [1.1.10]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ matrix.poetry-version }}
            - name: Install dependencies
              run: |
                  poetry install
            - name: Run checks
              run: |
                  poetry run flake8 --statistics --show-source
                  poetry run mypy .
