name: Lint & Mypy check

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint-check-job:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - uses: dschep/install-pipenv-action@v1
            - name: Install pipenv
              run: |
                  pip install pipenv
            - name: Install dependencies
              run: |
                  pipenv install --dev

            - name: Lint & Mypy check
              run: |
                  pipenv run flake8 --statistics --show-source
                  pipenv run mypy .
